/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class DynamicPanel extends javax.swing.JFrame {
    
    
    

    /**
     * Creates new form DynamicPanel
     */
    public DynamicPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCheckBox10 = new javax.swing.JCheckBox();
        jTextField12 = new javax.swing.JTextField();
        BodyPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        btnCheckout = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        orderPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btxMieAyam = new javax.swing.JCheckBox();
        btxMieAyamBakso = new javax.swing.JCheckBox();
        btxBaksoKerikil = new javax.swing.JCheckBox();
        btxBaksoBiasa = new javax.swing.JCheckBox();
        btxBaksoTenes = new javax.swing.JCheckBox();
        btxBaksoBeranak = new javax.swing.JCheckBox();
        btxBaksoSetan = new javax.swing.JCheckBox();
        btxNasiGoreng = new javax.swing.JCheckBox();
        btxMieGoreng = new javax.swing.JCheckBox();
        btxSotoAyam = new javax.swing.JCheckBox();
        btxLalapan = new javax.swing.JCheckBox();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        txt7 = new javax.swing.JTextField();
        txt8 = new javax.swing.JTextField();
        txt9 = new javax.swing.JTextField();
        txt10 = new javax.swing.JTextField();
        txt11 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btxTeh = new javax.swing.JCheckBox();
        btxKopi = new javax.swing.JCheckBox();
        btxLemonTea = new javax.swing.JCheckBox();
        btxNutrisari = new javax.swing.JCheckBox();
        btxJosua = new javax.swing.JCheckBox();
        btxThaiTea = new javax.swing.JCheckBox();
        btxCappucino = new javax.swing.JCheckBox();
        btxOvaltine = new javax.swing.JCheckBox();
        btxSyrup = new javax.swing.JCheckBox();
        btxJuice = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txt12 = new javax.swing.JTextField();
        txt13 = new javax.swing.JTextField();
        txt14 = new javax.swing.JTextField();
        txt15 = new javax.swing.JTextField();
        txt16 = new javax.swing.JTextField();
        txt17 = new javax.swing.JTextField();
        txt18 = new javax.swing.JTextField();
        txt19 = new javax.swing.JTextField();
        txt20 = new javax.swing.JTextField();
        txt21 = new javax.swing.JTextField();
        btxKerupukPangsit = new javax.swing.JCheckBox();
        btxBakwan = new javax.swing.JCheckBox();
        btxPentolGoreng = new javax.swing.JCheckBox();
        btxPentolSetan = new javax.swing.JCheckBox();
        txt22 = new javax.swing.JTextField();
        txt23 = new javax.swing.JTextField();
        txt24 = new javax.swing.JTextField();
        txt25 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        txtNAMA = new javax.swing.JTextField();
        btnPesan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        checkoutPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPesan = new javax.swing.JTextArea();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtTotalBayar = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txtDibayar = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel9.setText("Menu Minuman :");

        jLabel10.setText("Harga :");

        jLabel11.setText("Jumlah : ");

        jCheckBox10.setText("jCheckBox1");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });

        jTextField12.setText("jTextField1");
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Dynamic Panel");

        BodyPanel.setBackground(new java.awt.Color(255, 255, 255));

        menuPanel.setBackground(new java.awt.Color(255, 102, 0));
        menuPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        btnCheckout.setBackground(new java.awt.Color(255, 255, 255));
        btnCheckout.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btnCheckout.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\SI Restoran Icon\\list (2).png")); // NOI18N
        btnCheckout.setText("CHECKOUT");
        btnCheckout.setIconTextGap(10);
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(255, 255, 255));
        btnHome.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\SI Restoran Icon\\home24.png")); // NOI18N
        btnHome.setText("HOME");
        btnHome.setIconTextGap(10);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(255, 255, 255));
        btnLogOut.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btnLogOut.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\SI Restoran Icon\\logout 24.png")); // NOI18N
        btnLogOut.setText("LOG OUT");
        btnLogOut.setIconTextGap(10);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnAbout.setBackground(new java.awt.Color(255, 255, 255));
        btnAbout.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btnAbout.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\SI Restoran Icon\\about 24.png")); // NOI18N
        btnAbout.setText("ABOUT");
        btnAbout.setIconTextGap(10);
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        btnOrder.setBackground(new java.awt.Color(255, 255, 255));
        btnOrder.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btnOrder.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\SI Restoran Icon\\menu24.png")); // NOI18N
        btnOrder.setText("ORDER");
        btnOrder.setIconTextGap(10);
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        jLabel45.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\SI Restoran Icon\\dinner.png")); // NOI18N

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOrder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, menuPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel45)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        mainPanel.setBackground(new java.awt.Color(255, 102, 0));
        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        mainPanel.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(255, 255, 255));
        homePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0)));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel1.setText("Mie Ayam Bakso");

        jLabel46.setFont(new java.awt.Font("Elephant", 1, 48)); // NOI18N
        jLabel46.setText("MAS TEGAR");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap(233, Short.MAX_VALUE)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(227, 227, 227))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel46)
                .addContainerGap(298, Short.MAX_VALUE))
        );

        mainPanel.add(homePanel, "card2");

        orderPanel.setBackground(new java.awt.Color(255, 255, 255));
        orderPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0)));
        orderPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Mongolian Baiti", 0, 24)); // NOI18N
        jLabel2.setText("DAFTAR MENU");
        orderPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 225, 38));

        jLabel3.setFont(new java.awt.Font("Mongolian Baiti", 1, 12)); // NOI18N
        jLabel3.setText("Menu Makanan :");
        orderPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 91, -1, -1));

        jLabel4.setFont(new java.awt.Font("Mongolian Baiti", 1, 12)); // NOI18N
        jLabel4.setText("Harga :");
        orderPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 91, -1, -1));

        jLabel5.setFont(new java.awt.Font("Mongolian Baiti", 1, 12)); // NOI18N
        jLabel5.setText("Jumlah : ");
        orderPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 91, -1, -1));

        jLabel6.setFont(new java.awt.Font("Mongolian Baiti", 1, 12)); // NOI18N
        jLabel6.setText("Menu Minuman :");
        orderPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 91, -1, -1));

        jLabel7.setFont(new java.awt.Font("Mongolian Baiti", 1, 12)); // NOI18N
        jLabel7.setText("Harga :");
        orderPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 91, -1, -1));

        jLabel8.setFont(new java.awt.Font("Mongolian Baiti", 1, 12)); // NOI18N
        jLabel8.setText("Jumlah : ");
        orderPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 91, -1, -1));

        jLabel12.setFont(new java.awt.Font("Mongolian Baiti", 1, 12)); // NOI18N
        jLabel12.setText("Menu Snack :");
        orderPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 497, -1, -1));

        jLabel13.setFont(new java.awt.Font("Mongolian Baiti", 1, 12)); // NOI18N
        jLabel13.setText("Harga :");
        orderPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 497, -1, -1));

        jLabel14.setFont(new java.awt.Font("Mongolian Baiti", 1, 12)); // NOI18N
        jLabel14.setText("Jumlah : ");
        orderPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 497, -1, -1));

        btxMieAyam.setBackground(new java.awt.Color(255, 255, 255));
        btxMieAyam.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btxMieAyam.setText("Mie Ayam");
        btxMieAyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxMieAyamActionPerformed(evt);
            }
        });
        orderPanel.add(btxMieAyam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 116, -1, -1));

        btxMieAyamBakso.setBackground(new java.awt.Color(255, 255, 255));
        btxMieAyamBakso.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btxMieAyamBakso.setText("Mie Ayam Bakso");
        btxMieAyamBakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxMieAyamBaksoActionPerformed(evt);
            }
        });
        orderPanel.add(btxMieAyamBakso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 147, -1, -1));

        btxBaksoKerikil.setBackground(new java.awt.Color(255, 255, 255));
        btxBaksoKerikil.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btxBaksoKerikil.setText("Bakso Kerikil");
        btxBaksoKerikil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxBaksoKerikilActionPerformed(evt);
            }
        });
        orderPanel.add(btxBaksoKerikil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 178, -1, -1));

        btxBaksoBiasa.setBackground(new java.awt.Color(255, 255, 255));
        btxBaksoBiasa.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btxBaksoBiasa.setText("Bakso Biasa");
        btxBaksoBiasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxBaksoBiasaActionPerformed(evt);
            }
        });
        orderPanel.add(btxBaksoBiasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 209, -1, -1));

        btxBaksoTenes.setBackground(new java.awt.Color(255, 255, 255));
        btxBaksoTenes.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btxBaksoTenes.setText("Bakso Tenes");
        btxBaksoTenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxBaksoTenesActionPerformed(evt);
            }
        });
        orderPanel.add(btxBaksoTenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        btxBaksoBeranak.setBackground(new java.awt.Color(255, 255, 255));
        btxBaksoBeranak.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btxBaksoBeranak.setText("Bakso Beranak");
        btxBaksoBeranak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxBaksoBeranakActionPerformed(evt);
            }
        });
        orderPanel.add(btxBaksoBeranak, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 271, -1, -1));

        btxBaksoSetan.setBackground(new java.awt.Color(255, 255, 255));
        btxBaksoSetan.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btxBaksoSetan.setText("Bakso Setan");
        btxBaksoSetan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxBaksoSetanActionPerformed(evt);
            }
        });
        orderPanel.add(btxBaksoSetan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 302, -1, -1));

        btxNasiGoreng.setBackground(new java.awt.Color(255, 255, 255));
        btxNasiGoreng.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btxNasiGoreng.setText("Nasi Goreng");
        btxNasiGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxNasiGorengActionPerformed(evt);
            }
        });
        orderPanel.add(btxNasiGoreng, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 333, -1, -1));

        btxMieGoreng.setBackground(new java.awt.Color(255, 255, 255));
        btxMieGoreng.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btxMieGoreng.setText("Mie Goreng");
        btxMieGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxMieGorengActionPerformed(evt);
            }
        });
        orderPanel.add(btxMieGoreng, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 364, -1, -1));

        btxSotoAyam.setBackground(new java.awt.Color(255, 255, 255));
        btxSotoAyam.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btxSotoAyam.setText("Soto Ayam");
        btxSotoAyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxSotoAyamActionPerformed(evt);
            }
        });
        orderPanel.add(btxSotoAyam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 395, -1, -1));

        btxLalapan.setBackground(new java.awt.Color(255, 255, 255));
        btxLalapan.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btxLalapan.setText("Lalapan");
        btxLalapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxLalapanActionPerformed(evt);
            }
        });
        orderPanel.add(btxLalapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 426, -1, -1));

        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        orderPanel.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 117, 43, -1));

        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });
        orderPanel.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 148, 43, -1));

        txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt3ActionPerformed(evt);
            }
        });
        orderPanel.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 179, 43, -1));

        txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt4ActionPerformed(evt);
            }
        });
        orderPanel.add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 210, 43, -1));

        txt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt5ActionPerformed(evt);
            }
        });
        orderPanel.add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 241, 43, -1));

        txt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt6ActionPerformed(evt);
            }
        });
        orderPanel.add(txt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 272, 43, -1));

        txt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt7ActionPerformed(evt);
            }
        });
        orderPanel.add(txt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 303, 43, -1));

        txt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt8ActionPerformed(evt);
            }
        });
        orderPanel.add(txt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 334, 43, -1));

        txt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt9ActionPerformed(evt);
            }
        });
        orderPanel.add(txt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 365, 43, -1));

        txt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt10ActionPerformed(evt);
            }
        });
        orderPanel.add(txt10, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 396, 43, -1));

        txt11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt11ActionPerformed(evt);
            }
        });
        orderPanel.add(txt11, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 427, 43, -1));

        jLabel15.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel15.setText("Rp 15.000");
        orderPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 120, -1, -1));

        jLabel16.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel16.setText("Rp 20.000");
        orderPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 151, -1, -1));

        jLabel17.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel17.setText("Rp 15.000");
        orderPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 182, -1, -1));

        jLabel18.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel18.setText("Rp 15.000");
        orderPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 213, -1, -1));

        jLabel19.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel19.setText("Rp 25.000");
        orderPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 244, -1, -1));

        jLabel20.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel20.setText("Rp 25.000");
        orderPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 275, -1, -1));

        jLabel21.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel21.setText("Rp 25.000");
        orderPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 306, -1, -1));

        jLabel22.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel22.setText("Rp 20.000");
        orderPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 337, -1, -1));

        jLabel23.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel23.setText("Rp 20.000");
        orderPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 368, -1, -1));

        jLabel24.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel24.setText("Rp 20.000");
        orderPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 399, -1, -1));

        jLabel25.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel25.setText("Rp 25.000");
        orderPanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 430, -1, -1));

        btxTeh.setBackground(new java.awt.Color(255, 255, 255));
        btxTeh.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btxTeh.setText("Teh");
        btxTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxTehActionPerformed(evt);
            }
        });
        orderPanel.add(btxTeh, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 116, -1, -1));

        btxKopi.setBackground(new java.awt.Color(255, 255, 255));
        btxKopi.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btxKopi.setText("Kopi");
        btxKopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxKopiActionPerformed(evt);
            }
        });
        orderPanel.add(btxKopi, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 145, -1, -1));

        btxLemonTea.setBackground(new java.awt.Color(255, 255, 255));
        btxLemonTea.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btxLemonTea.setText("Lemon Tea");
        btxLemonTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxLemonTeaActionPerformed(evt);
            }
        });
        orderPanel.add(btxLemonTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 178, -1, -1));

        btxNutrisari.setBackground(new java.awt.Color(255, 255, 255));
        btxNutrisari.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btxNutrisari.setText("Nutrisari");
        btxNutrisari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxNutrisariActionPerformed(evt);
            }
        });
        orderPanel.add(btxNutrisari, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 209, -1, -1));

        btxJosua.setBackground(new java.awt.Color(255, 255, 255));
        btxJosua.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btxJosua.setText("Josua");
        btxJosua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxJosuaActionPerformed(evt);
            }
        });
        orderPanel.add(btxJosua, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 240, -1, -1));

        btxThaiTea.setBackground(new java.awt.Color(255, 255, 255));
        btxThaiTea.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btxThaiTea.setText("Bubble Thai Tea");
        btxThaiTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxThaiTeaActionPerformed(evt);
            }
        });
        orderPanel.add(btxThaiTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 271, -1, -1));

        btxCappucino.setBackground(new java.awt.Color(255, 255, 255));
        btxCappucino.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btxCappucino.setText("Bubble Cappucino");
        btxCappucino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxCappucinoActionPerformed(evt);
            }
        });
        orderPanel.add(btxCappucino, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 302, -1, -1));

        btxOvaltine.setBackground(new java.awt.Color(255, 255, 255));
        btxOvaltine.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btxOvaltine.setText("Bubble Ovaltine");
        btxOvaltine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxOvaltineActionPerformed(evt);
            }
        });
        orderPanel.add(btxOvaltine, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 333, -1, -1));

        btxSyrup.setBackground(new java.awt.Color(255, 255, 255));
        btxSyrup.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btxSyrup.setText("Bubble Syrup");
        btxSyrup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxSyrupActionPerformed(evt);
            }
        });
        orderPanel.add(btxSyrup, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 364, -1, -1));

        btxJuice.setBackground(new java.awt.Color(255, 255, 255));
        btxJuice.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btxJuice.setText("Bubble Juice");
        btxJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxJuiceActionPerformed(evt);
            }
        });
        orderPanel.add(btxJuice, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 395, -1, -1));

        jLabel26.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel26.setText("Rp 5.000");
        orderPanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 119, -1, -1));

        jLabel27.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel27.setText("Rp 5.000");
        orderPanel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 150, -1, -1));

        jLabel28.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel28.setText("Rp 5.000");
        orderPanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 181, 50, -1));

        jLabel29.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel29.setText("Rp 5.000");
        orderPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 212, 50, -1));

        jLabel30.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel30.setText("Rp 5.000");
        orderPanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 243, 50, -1));

        jLabel31.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel31.setText("Rp 10.000");
        orderPanel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 275, -1, -1));

        jLabel32.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel32.setText("Rp 10.000");
        orderPanel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 305, -1, -1));

        jLabel33.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel33.setText("Rp 10.000");
        orderPanel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 336, -1, -1));

        jLabel34.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel34.setText("Rp 10.000");
        orderPanel.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 367, -1, -1));

        jLabel35.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel35.setText("Rp 10.000");
        orderPanel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 398, -1, -1));

        txt12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt12ActionPerformed(evt);
            }
        });
        orderPanel.add(txt12, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 116, 43, -1));

        txt13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt13ActionPerformed(evt);
            }
        });
        orderPanel.add(txt13, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 147, 43, -1));

        txt14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt14ActionPerformed(evt);
            }
        });
        orderPanel.add(txt14, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 178, 43, -1));

        txt15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt15ActionPerformed(evt);
            }
        });
        orderPanel.add(txt15, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 209, 43, -1));

        txt16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt16ActionPerformed(evt);
            }
        });
        orderPanel.add(txt16, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 240, 43, -1));

        txt17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt17ActionPerformed(evt);
            }
        });
        orderPanel.add(txt17, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 271, 43, -1));

        txt18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt18ActionPerformed(evt);
            }
        });
        orderPanel.add(txt18, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 302, 43, -1));

        txt19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt19ActionPerformed(evt);
            }
        });
        orderPanel.add(txt19, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 333, 43, -1));

        txt20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt20ActionPerformed(evt);
            }
        });
        orderPanel.add(txt20, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 364, 43, -1));

        txt21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt21ActionPerformed(evt);
            }
        });
        orderPanel.add(txt21, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 395, 43, -1));

        btxKerupukPangsit.setBackground(new java.awt.Color(255, 255, 255));
        btxKerupukPangsit.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btxKerupukPangsit.setText("Kerupuk Pangsit");
        btxKerupukPangsit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxKerupukPangsitActionPerformed(evt);
            }
        });
        orderPanel.add(btxKerupukPangsit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 532, -1, -1));

        btxBakwan.setBackground(new java.awt.Color(255, 255, 255));
        btxBakwan.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btxBakwan.setText("Bakwan");
        btxBakwan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxBakwanActionPerformed(evt);
            }
        });
        orderPanel.add(btxBakwan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 565, -1, -1));

        btxPentolGoreng.setBackground(new java.awt.Color(255, 255, 255));
        btxPentolGoreng.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btxPentolGoreng.setText("Pentol Goreng Mayo");
        btxPentolGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxPentolGorengActionPerformed(evt);
            }
        });
        orderPanel.add(btxPentolGoreng, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 596, -1, -1));

        btxPentolSetan.setBackground(new java.awt.Color(255, 255, 255));
        btxPentolSetan.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        btxPentolSetan.setText("Pentol Setan");
        btxPentolSetan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxPentolSetanActionPerformed(evt);
            }
        });
        orderPanel.add(btxPentolSetan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 627, -1, -1));

        txt22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt22ActionPerformed(evt);
            }
        });
        orderPanel.add(txt22, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 533, 43, -1));

        txt23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt23ActionPerformed(evt);
            }
        });
        orderPanel.add(txt23, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 566, 43, -1));

        txt24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt24ActionPerformed(evt);
            }
        });
        orderPanel.add(txt24, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 597, 43, -1));

        txt25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt25ActionPerformed(evt);
            }
        });
        orderPanel.add(txt25, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 628, 43, -1));

        jLabel36.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel36.setText("Rp 5.000");
        orderPanel.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 536, -1, -1));

        jLabel37.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel37.setText("Rp 5.000");
        orderPanel.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 569, -1, -1));

        jLabel38.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel38.setText("Rp 15.000");
        orderPanel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 600, -1, -1));

        jLabel39.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel39.setText("Rp 15.000");
        orderPanel.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 631, -1, -1));

        jLabel41.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        jLabel41.setText("NAMA");
        orderPanel.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 497, -1, -1));

        txtNAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNAMAActionPerformed(evt);
            }
        });
        orderPanel.add(txtNAMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 494, 284, -1));

        btnPesan.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        btnPesan.setText("PESAN");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });
        orderPanel.add(btnPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 532, -1, -1));

        btnReset.setFont(new java.awt.Font("Mongolian Baiti", 0, 11)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        orderPanel.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 532, -1, -1));

        mainPanel.add(orderPanel, "card3");

        checkoutPanel.setBackground(new java.awt.Color(255, 255, 255));
        checkoutPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 102, 0)));

        txtPesan.setColumns(20);
        txtPesan.setRows(5);
        jScrollPane1.setViewportView(txtPesan);

        jLabel40.setFont(new java.awt.Font("Mongolian Baiti", 0, 24)); // NOI18N
        jLabel40.setText("CHECK OUT");

        jLabel42.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jLabel42.setText("Total Bayar");

        jLabel43.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jLabel43.setText("Uang Dibayar");

        jLabel44.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jLabel44.setText("Kembalian");

        txtKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKembalianActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CETAK NOTA");

        javax.swing.GroupLayout checkoutPanelLayout = new javax.swing.GroupLayout(checkoutPanel);
        checkoutPanel.setLayout(checkoutPanelLayout);
        checkoutPanelLayout.setHorizontalGroup(
            checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutPanelLayout.createSequentialGroup()
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(checkoutPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(checkoutPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(checkoutPanelLayout.createSequentialGroup()
                                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel43)
                                    .addComponent(jLabel42)
                                    .addComponent(jLabel44))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKembalian)
                                    .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTotalBayar, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                        .addComponent(txtDibayar)))))))
                .addContainerGap(498, Short.MAX_VALUE))
        );
        checkoutPanelLayout.setVerticalGroup(
            checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(txtDibayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        mainPanel.add(checkoutPanel, "card4");

        javax.swing.GroupLayout BodyPanelLayout = new javax.swing.GroupLayout(BodyPanel);
        BodyPanel.setLayout(BodyPanelLayout);
        BodyPanelLayout.setHorizontalGroup(
            BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BodyPanelLayout.setVerticalGroup(
            BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        // TODO add your handling code here:

        // remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // add panel
        mainPanel.add(checkoutPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:

        // remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // add panel
        mainPanel.add(homePanel);
        mainPanel.repaint();
        mainPanel.revalidate();

    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda yakin ingin keluar ?", "Peringatan", dialogBtn);
        
        if (dialogResult == 0) {
            // true condition
            System.exit(0);
        } else {
            // false condition
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
        AboutPanel n = new AboutPanel();
        n.setVisible(true);
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:

        // remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // add panel
        mainPanel.add(orderPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnOrderActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void txt21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt21ActionPerformed

    private void txt20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt20ActionPerformed

    private void txt19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt19ActionPerformed

    private void txt18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt18ActionPerformed

    private void txt17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt17ActionPerformed

    private void txt16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt16ActionPerformed

    private void txt15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt15ActionPerformed

    private void txt14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt14ActionPerformed

    private void txt13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt13ActionPerformed

    private void txt12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt12ActionPerformed

    private void btxJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxJuiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxJuiceActionPerformed

    private void btxSyrupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxSyrupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxSyrupActionPerformed

    private void btxOvaltineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxOvaltineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxOvaltineActionPerformed

    private void btxCappucinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxCappucinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxCappucinoActionPerformed

    private void btxThaiTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxThaiTeaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxThaiTeaActionPerformed

    private void btxJosuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxJosuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxJosuaActionPerformed

    private void btxNutrisariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxNutrisariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxNutrisariActionPerformed

    private void btxLemonTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxLemonTeaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxLemonTeaActionPerformed

    private void btxKopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxKopiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxKopiActionPerformed

    private void btxTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxTehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxTehActionPerformed

    private void txt11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt11ActionPerformed

    private void txt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt10ActionPerformed

    private void txt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt9ActionPerformed

    private void txt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt8ActionPerformed

    private void txt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt7ActionPerformed

    private void txt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt6ActionPerformed

    private void txt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt5ActionPerformed

    private void txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt4ActionPerformed

    private void txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt3ActionPerformed

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void btxLalapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxLalapanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxLalapanActionPerformed

    private void btxSotoAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxSotoAyamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxSotoAyamActionPerformed

    private void btxMieGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxMieGorengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxMieGorengActionPerformed

    private void btxNasiGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxNasiGorengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxNasiGorengActionPerformed

    private void btxBaksoSetanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxBaksoSetanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxBaksoSetanActionPerformed

    private void btxBaksoBeranakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxBaksoBeranakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxBaksoBeranakActionPerformed

    private void btxBaksoTenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxBaksoTenesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxBaksoTenesActionPerformed

    private void btxBaksoBiasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxBaksoBiasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxBaksoBiasaActionPerformed

    private void btxBaksoKerikilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxBaksoKerikilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxBaksoKerikilActionPerformed

    private void btxMieAyamBaksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxMieAyamBaksoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxMieAyamBaksoActionPerformed

    private void btxMieAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxMieAyamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxMieAyamActionPerformed

    private void btxKerupukPangsitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxKerupukPangsitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxKerupukPangsitActionPerformed

    private void btxBakwanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxBakwanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxBakwanActionPerformed

    private void btxPentolGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxPentolGorengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxPentolGorengActionPerformed

    private void btxPentolSetanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxPentolSetanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btxPentolSetanActionPerformed

    private void txt22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt22ActionPerformed

    private void txt23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt23ActionPerformed

    private void txt24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt24ActionPerformed

    private void txt25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt25ActionPerformed

    private void txtNAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNAMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNAMAActionPerformed

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        // TODO add your handling code here:

        String tampil;
        tampil = "";
        int bayar = 0;

        if (btxMieAyam.isSelected()) {
            int jumlah = Integer.parseInt(txt1.getText());
            int total;
            total = jumlah * 15000;
            bayar = bayar + total;
            tampil += btxMieAyam.getText() +  " Rp 15.000 " + " x " + jumlah + " = " + total + "\n";
        }
        if (btxMieAyamBakso.isSelected()) {
            int jumlah = Integer.parseInt(txt2.getText());
            int total;
            total = jumlah * 20000;
            bayar = bayar + total;
            tampil += btxMieAyamBakso.getText() +   " Rp 20.000 " + " x " + jumlah + " = " + total + "\n";
        }
        if (btxBaksoKerikil.isSelected()) {
            int jumlah = Integer.parseInt(txt3.getText());
            int total;
            total = jumlah * 15000;
            bayar = bayar + total;
            tampil += btxBaksoKerikil.getText() +  " Rp 15.000 " + " x " + jumlah + " = " + total + "\n";
        }
        if (btxBaksoBiasa.isSelected()) {
            int jumlah = Integer.parseInt(txt4.getText());
            int total;
            total = jumlah * 15000;
            bayar = bayar + total;
            tampil += btxBaksoBiasa.getText() +  " Rp 15.000 " + " x " + jumlah + " = " + total + "\n";
        }
        if (btxBaksoTenes.isSelected()) {
            int jumlah = Integer.parseInt(txt5.getText());
            int total;
            total = jumlah * 25000;
            bayar = bayar + total;
            tampil += btxBaksoTenes.getText() +  " Rp 25.000 " + " x " + jumlah + " = " + total + "\n";
        }
        if (btxBaksoBeranak.isSelected()) {
            int jumlah = Integer.parseInt(txt6.getText());
            int total;
            total = jumlah * 25000;
            bayar = bayar + total;
            tampil += btxBaksoBeranak.getText() +  " Rp 25.000 " + " x " + jumlah + " = " + total + "\n";
        }
        if (btxBaksoSetan.isSelected()) {
            int jumlah = Integer.parseInt(txt7.getText());
            int total;
            total = jumlah * 25000;
            bayar = bayar + total;
            tampil += btxBaksoSetan.getText() +  " Rp 25.000 " + " x " + jumlah + " = " + total + "\n";
        }
        if (btxNasiGoreng.isSelected()) {
            int jumlah = Integer.parseInt(txt8.getText());
            int total;
            total = jumlah * 20000;
            bayar = bayar + total;
            tampil += btxNasiGoreng.getText() +  " Rp 20.000 " + " x " + jumlah + " = " + total + "\n";
        }
        if (btxMieGoreng.isSelected()) {
            int jumlah = Integer.parseInt(txt9.getText());
            int total;
            total = jumlah * 20000;
            bayar = bayar + total;
            tampil += btxMieGoreng.getText() +  " Rp 20.000 " + " x " + jumlah + " = " + total + "\n";
        }
        if (btxSotoAyam.isSelected()) {
            int jumlah = Integer.parseInt(txt10.getText());
            int total;
            total = jumlah * 20000;
            bayar = bayar + total;
            tampil += btxSotoAyam.getText() +  " Rp20.000 " + " x " + jumlah + " = " + total + "\n";
        }
        if (btxLalapan.isSelected()) {
            int jumlah = Integer.parseInt(txt11.getText());
            int total;
            total = jumlah * 25000;
            bayar = bayar + total;
            tampil += btxLalapan.getText() +  " Rp 25.000 " + " x " + jumlah + " = " + total + "\n";
        }
        if (btxTeh.isSelected()) {
            int jumlah = Integer.parseInt(txt12.getText());
            int total;
            total = jumlah * 5000;
            bayar = bayar + total;
            tampil += btxTeh.getText() +  " Rp 5.000 " + " x " + jumlah + " = " + total + "\n";
        }
        if (btxKopi.isSelected()) {
            int jumlah = Integer.parseInt(txt13.getText());
            int total;
            total = jumlah * 5000;
            bayar = bayar + total;
            tampil += btxKopi.getText() +  " Rp 5.000 " + " x " + jumlah + " = " + total + "\n";
        }
        if (btxLemonTea.isSelected()) {
            int jumlah = Integer.parseInt(txt14.getText());
            int total;
            total = jumlah * 5000;
            bayar = bayar + total;
            tampil += btxLemonTea.getText() +  " Rp 5.000 " + " x " + jumlah + " = " + total + "\n";
        }
        if (btxNutrisari.isSelected()) {
            int jumlah = Integer.parseInt(txt15.getText());
            int total;
            total = jumlah * 5000;
            bayar = bayar + total;
            tampil += btxNutrisari.getText() +  " Rp 5.000 " + " x " + jumlah + " = " + total + "\n";
        }
        if (btxJosua.isSelected()) {
            int jumlah = Integer.parseInt(txt16.getText());
            int total;
            total = jumlah * 5000;
            bayar = bayar + total;
            tampil += btxJosua.getText() +  " Rp 5.000 " + " x " + jumlah + " = " + total + "\n";
        }
        if (btxThaiTea.isSelected()) {
            int jumlah = Integer.parseInt(txt17.getText());
            int total;
            total = jumlah * 10000;
            bayar = bayar + total;
            tampil += btxThaiTea.getText() +  " Rp 10.000 " + " x " + jumlah + " = " + total + "\n";
        }
        if (btxCappucino.isSelected()) {
            int jumlah = Integer.parseInt(txt18.getText());
            int total;
            total = jumlah * 10000;
            bayar = bayar + total;
            tampil += btxCappucino.getText() +  " Rp 10.000 " + " x " + jumlah + " = " + total + "\n";
        }
        if (btxOvaltine.isSelected()) {
            int jumlah = Integer.parseInt(txt19.getText());
            int total;
            total = jumlah * 10000;
            bayar = bayar + total;
            tampil += btxOvaltine.getText() +  " Rp 10.000 " + " x " + jumlah + " = " + total + "\n";
        }
        if (btxSyrup.isSelected()) {
            int jumlah = Integer.parseInt(txt20.getText());
            int total;
            total = jumlah * 10000;
            bayar = bayar + total;
            tampil += btxSyrup.getText() +  " Rp 10.000 " + " x " + jumlah + " = " + total + "\n";
        }
        if (btxJuice.isSelected()) {
            int jumlah = Integer.parseInt(txt21.getText());
            int total;
            total = jumlah * 10000;
            bayar = bayar + total;
            tampil += btxJuice.getText() +  " Rp 10.000 " + " x " + jumlah + " = " + total + "\n";
        }
        if (btxKerupukPangsit.isSelected()) {
            int jumlah = Integer.parseInt(txt22.getText());
            int total;
            total = jumlah * 5000;
            bayar = bayar + total;
            tampil += btxKerupukPangsit.getText() +  " Rp 5.000 " + " x " + jumlah + " = " + total + "\n";
        }
        if (btxBakwan.isSelected()) {
            int jumlah = Integer.parseInt(txt23.getText());
            int total;
            total = jumlah * 5000;
            bayar = bayar + total;
            tampil += btxBakwan.getText() +  " Rp 5.000 " + " x " + jumlah + " = " + total + "\n";
        }
        if (btxPentolGoreng.isSelected()) {
            int jumlah = Integer.parseInt(txt24.getText());
            int total;
            total = jumlah * 15000;
            bayar = bayar + total;
            tampil += btxPentolGoreng.getText() +  " Rp 15.000 " + " x " + jumlah + " = " + total + "\n";
        }
        if (btxPentolSetan.isSelected()) {
            int jumlah = Integer.parseInt(txt25.getText());
            int total;
            total = jumlah * 15000;
            bayar = bayar + total;
            tampil += btxPentolSetan.getText() +  " Rp 15.000 " + " x " + jumlah + " = " + total + "\n";
        }
        
        // remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // add panel
        mainPanel.add(checkoutPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        txtPesan.setText(tampil);
        
        txtTotalBayar.setText("" + bayar);
    }//GEN-LAST:event_btnPesanActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txt1.setText("");
        txt2.setText("");
        txt3.setText("");
        txt4.setText("");
        txt5.setText("");
        txt6.setText("");
        txt7.setText("");
        txt8.setText("");
        txt9.setText("");
        txt10.setText("");
        txt11.setText("");
        txt12.setText("");
        txt13.setText("");
        txt14.setText("");
        txt15.setText("");
        txt16.setText("");
        txt17.setText("");
        txt18.setText("");
        txt19.setText("");
        txt20.setText("");
        txt21.setText("");
        txt22.setText("");
        txt23.setText("");
        txt24.setText("");
        txt25.setText("");
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKembalianActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtKembalianActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(txtTotalBayar.getText());
        int b = Integer.parseInt(txtDibayar.getText());
        
        int c = b - a;
        
        txtKembalian.setText("" + c);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DynamicPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DynamicPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DynamicPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DynamicPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DynamicPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BodyPanel;
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnPesan;
    private javax.swing.JButton btnReset;
    private javax.swing.JCheckBox btxBaksoBeranak;
    private javax.swing.JCheckBox btxBaksoBiasa;
    private javax.swing.JCheckBox btxBaksoKerikil;
    private javax.swing.JCheckBox btxBaksoSetan;
    private javax.swing.JCheckBox btxBaksoTenes;
    private javax.swing.JCheckBox btxBakwan;
    private javax.swing.JCheckBox btxCappucino;
    private javax.swing.JCheckBox btxJosua;
    private javax.swing.JCheckBox btxJuice;
    private javax.swing.JCheckBox btxKerupukPangsit;
    private javax.swing.JCheckBox btxKopi;
    private javax.swing.JCheckBox btxLalapan;
    private javax.swing.JCheckBox btxLemonTea;
    private javax.swing.JCheckBox btxMieAyam;
    private javax.swing.JCheckBox btxMieAyamBakso;
    private javax.swing.JCheckBox btxMieGoreng;
    private javax.swing.JCheckBox btxNasiGoreng;
    private javax.swing.JCheckBox btxNutrisari;
    private javax.swing.JCheckBox btxOvaltine;
    private javax.swing.JCheckBox btxPentolGoreng;
    private javax.swing.JCheckBox btxPentolSetan;
    private javax.swing.JCheckBox btxSotoAyam;
    private javax.swing.JCheckBox btxSyrup;
    private javax.swing.JCheckBox btxTeh;
    private javax.swing.JCheckBox btxThaiTea;
    private javax.swing.JPanel checkoutPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel orderPanel;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt10;
    private javax.swing.JTextField txt11;
    private javax.swing.JTextField txt12;
    private javax.swing.JTextField txt13;
    private javax.swing.JTextField txt14;
    private javax.swing.JTextField txt15;
    private javax.swing.JTextField txt16;
    private javax.swing.JTextField txt17;
    private javax.swing.JTextField txt18;
    private javax.swing.JTextField txt19;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt20;
    private javax.swing.JTextField txt21;
    private javax.swing.JTextField txt22;
    private javax.swing.JTextField txt23;
    private javax.swing.JTextField txt24;
    private javax.swing.JTextField txt25;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    private javax.swing.JTextField txt9;
    private javax.swing.JTextField txtDibayar;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtNAMA;
    private javax.swing.JTextArea txtPesan;
    private javax.swing.JTextField txtTotalBayar;
    // End of variables declaration//GEN-END:variables
}
